services:
  db:
    container_name: postgres
    image: postgres:bookworm
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '3000:${PORT}'
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SCHEMA: ${DB_SCHEMA}
      PAYMENT_API_URL: ${PAYMENT_API_URL}
      PAYMENT_API_PUBLIC_API_KEY: ${PAYMENT_API_PUBLIC_API_KEY}
      PAYMENT_API_PRIVATE_API_KEY: ${PAYMENT_API_PRIVATE_API_KEY}
      PAYMENT_API_SIGNATURE: ${PAYMENT_API_SIGNATURE}
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  db_data:
