name: Generate Coverage Badge

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'iron-alpine'

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage
        run: npm run test:cov

      - name: Generate coverage badge
        uses: jaywcjlove/coverage-badges-cli@main
        with:
          source: coverage/coverage-summary.json
          output: coverage/badges.svg
          jsonPath: totals.percent_covered

      - name: Deploy badge
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
